sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 10.194.61.205
    port: 3306
    database: sky_take_out
    username: peak
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: peak-sky
  redis:
    host: 10.194.61.205
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxa2c2dcc721530585
    secret: 07b76cfabb2133c31679b8be4a7ed559

    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
